### ISSUE TITLE
Zeplin Link does not work

### ISSUE THREAD

**Issue by trystan2k** [payvision-development/recruitment-challenges#4]
Hi there !

I was about to start the project for FrontEnd Software Engineer but it seems that the Zelin link does not work: https://scene.zeplin.io/project/5aba58ec2ad5c9a98d97c76e. It returns a 'Not Found'

Could you please verify ?

Thank you !

**Comment by leonardopoza** [comment]
Hi,

I have checked and is working perfectly. Please let us know if you continue having problems. thanks
